# generated by datamodel-codegen:
#   filename:  https://api.cosmicds.cfa.harvard.edu/hubbles_law/docs.json
#
# DO NOT EDIT — regenerate with: scripts/generate_models.sh
#   timestamp: 2026-06-09T01:28:57+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, EmailStr, Field, RootModel


class Educator(BaseModel):
    id: int
    verified: bool
    verification_code: str
    email: str
    username: str
    first_name: str
    last_name: str
    password: str
    institution: str
    gender: str
    ip: str
    lat: str
    lon: str
    profile_created: AwareDatetime
    visits: int
    last_visit: AwareDatetime
    last_visit_ip: str


class Student(BaseModel):
    id: int
    verification_code: str
    email: str
    username: str
    password: str
    institution: str
    gender: str
    ip: str
    lat: str
    lon: str
    profile_created: AwareDatetime
    visits: int
    last_visit: AwareDatetime
    last_visit_ip: str
    team_member: str
    dummy: bool


class Status(Enum):
    seed = 'seed'
    real_good_data = 'real_good_data'
    real_bad_data = 'real_bad_data'
    test_good_data = 'test_good_data'
    test_bad_data = 'test_bad_data'


class Class(BaseModel):
    id: int
    name: str
    educator_id: int
    created: AwareDatetime
    updated: AwareDatetime | None = None
    active: bool
    code: str
    asynchronous: bool
    test: bool
    seed: bool
    expected_size: int
    status: Status | None = None


class Stage(BaseModel):
    story_name: str
    stage_name: str
    stage_index: int | None = None


class StageState(BaseModel):
    student_id: int
    story_name: str
    stage_name: str
    state: dict[str, Any]
    last_modified: AwareDatetime


class StoryState(BaseModel):
    student_id: int
    story_name: str
    story_state: dict[str, Any]
    last_modified: AwareDatetime


class Question(BaseModel):
    id: int
    tag: str
    text: str
    shorthand: str
    story_name: str
    version: int
    created: AwareDatetime
    answers_text: dict[str, Any]
    correct_answers: dict[str, Any]
    neutral_answers: dict[str, Any]


class ClassStories(BaseModel):
    class_id: int
    story_name: str
    active: bool


class User(RootModel[Any]):
    root: Any


class EducatorCreationInfo(BaseModel):
    first_name: str
    last_name: str
    password: str
    email: EmailStr
    username: str
    institution: str | None = None
    age: float | None = None
    gender: str | None = None


class Status1(Enum):
    bad_request = 'bad_request'
    ok = 'ok'
    email_already_exists = 'email_already_exists'
    error = 'error'


class EducatorCreated(BaseModel):
    educator_info: Any
    status: Status1
    success: bool


class StudentCreationInfo(BaseModel):
    username: str
    password: str
    email: EmailStr | None = None
    age: float | None = None
    gender: str | None = None
    institution: str | None = None
    classroom_code: str | None = None


class StudentCreated(BaseModel):
    educator_info: Any | None = None
    status: Status1
    success: bool


class ClassCreationInfo(BaseModel):
    educator_id: float
    name: str
    expected_size: float
    asynchronous: bool | None = None
    story_name: str | None = None


class ClassCreated(BaseModel):
    class_info: Any | None = None


class QuestionCreationInfo(BaseModel):
    text: str
    shorthand: str
    story_name: str
    answers_text: list[str] | None = None
    correct_answers: list[int] | None = None
    neutral_answers: list[int] | None = None
    version: int | None = None


class Error(BaseModel):
    error: str = Field(..., description='A message detailing why the operation failed')


class Galaxy(BaseModel):
    id: int
    name: str
    type: str
    element: str
    spec_marked_bad: int
    spec_is_good: int
    spec_checked: int
    tileload_marked_bad: int


class HubbleStudentData(BaseModel):
    student_id: int
    hubble_fit_unit: str | None = None
    age_unit: str | None = None
    last_data_update: AwareDatetime


class HubbleClassData(BaseModel):
    class_id: int
    hubble_fit_unit: str | None = None
    age_unit: str | None = None
    last_data_update: AwareDatetime


class HubbleMeasurementInput(BaseModel):
    student_id: int
    galaxy_id: int | None = None
    galaxy_name: str | None = None
    rest_wave_value: float | None = None
    rest_wave_unit: str | None = None
    obs_wave_value: float | None = None
    obs_wave_unit: str | None = None
    velocity_value: float | None = None
    velocity_unit: str | None = None
    ang_size_value: float | None = None
    ang_size_unit: str | None = None
    est_dist_value: float | None = None
    est_dist_unit: str | None = None
    brightness: float | None = None


class HubbleMeasurement(BaseModel):
    student_id: int
    galaxy_id: int
    galaxy_name: str | None = None
    rest_wave_value: float | None = None
    rest_wave_unit: str | None = None
    obs_wave_value: float | None = None
    obs_wave_unit: str | None = None
    velocity_value: float | None = None
    velocity_unit: str | None = None
    ang_size_value: float | None = None
    ang_size_unit: str | None = None
    est_dist_value: float | None = None
    est_dist_unit: str | None = None
    brightness: float | None = None


class HubbleSampleMeasurementInput(BaseModel):
    student_id: int
    galaxy_id: int | None = None
    galaxy_name: str | None = None
    rest_wave_value: float | None = None
    rest_wave_unit: str | None = None
    obs_wave_value: float | None = None
    obs_wave_unit: str | None = None
    velocity_value: float | None = None
    velocity_unit: str | None = None
    ang_size_value: float | None = None
    ang_size_unit: str | None = None
    est_dist_value: float | None = None
    est_dist_unit: str | None = None
    brightness: float | None = None
    measurement_number: str | None = None


class HubbleSampleMeasurement(BaseModel):
    student_id: int
    galaxy_id: int
    galaxy_name: str | None = None
    rest_wave_value: float | None = None
    rest_wave_unit: str | None = None
    obs_wave_value: float | None = None
    obs_wave_unit: str | None = None
    velocity_value: float | None = None
    velocity_unit: str | None = None
    ang_size_value: float | None = None
    ang_size_unit: str | None = None
    est_dist_value: float | None = None
    est_dist_unit: str | None = None
    brightness: float | None = None
    measurement_number: str | None = None


class MinimalHubbleMeasurement(BaseModel):
    student_id: int
    galaxy_id: int
    velocity_value: float
    est_dist_value: float
    class_id: int


class MinimalHubbleStudentData(BaseModel):
    student_id: int
    age_value: float
    class_id: int


class Element(Enum):
    H_α = 'H-α'
    Mg_I = 'Mg-I'


class MinimalGalaxy(BaseModel):
    id: int
    ra: float
    decl: float
    z: float
    type: float
    name: str
    element: Element
